services:
  frontend:
    container_name: mathboard2-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mathboard2-frontend:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
